#!/bin/bash
if [ "$EUID" -ne 0 ]
	then echo "Yonetici olarak calistirin"
else
apt update -y
apt install autoconf libcurl4-openssl-dev libjansson-dev openssl libssl-dev gcc gawk automake git -y
git clone https://github.com/lucasjones/cpuminer-multi.git
cd cpuminer-multi
./autogen.sh
./configure
make
printf "Klasorun adını degistireblirssiniz ./MinerMonero -a cryptonight -o stratum+tcp://pool.usxmrpool.com:7777 -u wallet adresinizi yazınız -p x -t 4"
fi
